### PR TITLE
feat: Add redux framework

### PR DESCRIPTION
**Pull request by LazyAfternoons**
- [x] I've added a short description of the entry that
      clarifies what it does and why it's useful
- [x] I've added links to the entry's documentation and/or
      website
- [x] My frontmatter is correct, complete and follows the
      format specified in the [README](../README.md)
- [x] In case the entry is in the `adopt` category: I've
      added at least one reference to showcase the entry usage
      among our organization
- [x] I've described at least one use case for the entry

### CODE REVIEW

**Comment by gunzip** [comment]
I'm skeptical about the proposal to include redux into the adopt ring, expecially for web. You can build a decent web UX without using redux nowadays, so imho iredux does not fit the definition: "items when we think it would be a poor and potentially irresponsible choice not to use them".

**Comment by LazyAfternoons** [comment]
> I'm skeptical about the proposal to include redux into the adopt ring, expecially for web. You can build a decent web UX without using redux nowadays, so imho redux does not fit the definition: "items when we think it would be a poor and potentially irresponsible choice not to use them". Maybe trial fits better?

The definition of the adopt ring is the following one, according to the guidelines: 

> Adopt: We can clearly recommend this technology. We have used it for longer period of time in many teams and it has proven to be stable and useful.

I honestly think redux perfectly fits this definition for us even thought many other state management frameworks have been proven to be stable as much as redux. However it still remains very relevant choice for large React applications.

**Comment by francescopersico** [comment]
My vote is for the adopt ring also to represent the actual state of our codebase.

**Comment by gunzip** [comment]
@francescopersico if you approve the PR we can merge this

**Review by francescopersico — APPROVED** [review]

**Pull request merged**
