### PR TITLE
Add GraalVM to tool

### PR DESCRIPTION
**Pull request by lucaconsalvi**
- [x] I've added a short description of the entry that
      clarifies what it does and why it's useful
- [x] I've added links to the entry's documentation and/or
      website
- [x] My frontmatter is correct, complete and follows the
      format specified in the [README](../README.md)
- [x] In case the entry is in the `adopt` category: I've
      added at least one reference to showcase the entry usage
      among our organization
- [x] I've described at least one use case for the entry

### CODE REVIEW

**Comment by gunzip** [comment]
do you think it might be worth to put graalvm in its own entry as it may be used with quarkus as well?

**Comment by lucaconsalvi** [comment]
> do you think it might be worth to put graalvm in its own entry as it may be used with quarkus as well?

Thank you for the observation! 😁
The fact is that we adopt GraalVM with SpringBoot, and we don't know how it "reacts" with a different stack. So yes, of course, we can just insert GraalVM and we can leave the use case with SpringBoot. I also thought that when I inserted it, but to be more accurate we just adopted GraalVM with Sprint Boot and not in general. 🤔

**Comment by gunzip** [comment]
Indeed, it's best to keep only GraalVM in this entry. 

Note that there's a separate entry dedicated exclusively to Spring Boot:

https://github.com/pagopa/technology-radar/pull/27

**Comment by manuraf** [comment]
I'm agree to maintain only GraalVM in this entry. 

I agree with classifying the tool as 'adopt' for its JVM function and Java compilation. However, I still have some doubts about its native compilation for more complex microservices; I would wait to have a more complex use case in the company that uses more complex libraries. 

For example, for Quarkus you have to follow some tips and tricks for getting around problems that might arise when attempting to run Java applications as native executables. Look at [here](https://quarkus.io/guides/writing-native-applications-tips)

**Review by iwoak — APPROVED** [review]

**Pull request merged**
